[package]
name = "boost_ratio"
description = "Boost C++ library boost_ratio packaged using Zanbil"
version = "0.1.0"
edition = "2024"
links = "boost_ratio"
license = "BSL-1.0"
repository = "https://github.com/zanbilify/boost_ratio"

[package.metadata.zanbil]
make_dependencies_public = true

[dependencies]

[build-dependencies]
zanbil-boost-build = "0.1.0"
